title: Xuan FENG's Log
description: Archive my thoughts and notes.

author: Xuan FENG
description:  my logs.
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" 
  back_home_text: ".." 
  date_format: "%Y-%m-%d"
  show_description: false 

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
